BEGIN
CREATE (:`Station`:`UNIQUE IMPORT LABEL` {`name`:"A", `UNIQUE IMPORT ID`:0});
CREATE (:`Station`:`UNIQUE IMPORT LABEL` {`name`:"B", `UNIQUE IMPORT ID`:20});
CREATE (:`Station`:`UNIQUE IMPORT LABEL` {`name`:"D", `UNIQUE IMPORT ID`:21});
CREATE (:`Station`:`UNIQUE IMPORT LABEL` {`name`:"E", `UNIQUE IMPORT ID`:22});
CREATE (:`Station`:`UNIQUE IMPORT LABEL` {`name`:"F", `UNIQUE IMPORT ID`:23});
CREATE (:`Station`:`UNIQUE IMPORT LABEL` {`name`:"C", `UNIQUE IMPORT ID`:40});
CREATE (:`Station`:`UNIQUE IMPORT LABEL` {`name`:"G", `UNIQUE IMPORT ID`:41});
CREATE (:`Station`:`UNIQUE IMPORT LABEL` {`name`:"I", `UNIQUE IMPORT ID`:42});
CREATE (:`Station`:`UNIQUE IMPORT LABEL` {`name`:"J", `UNIQUE IMPORT ID`:43});
CREATE (:`Station`:`UNIQUE IMPORT LABEL` {`name`:"H", `UNIQUE IMPORT ID`:44});
COMMIT
BEGIN
CREATE CONSTRAINT ON (node:`UNIQUE IMPORT LABEL`) ASSERT node.`UNIQUE IMPORT ID` IS UNIQUE;
COMMIT
SCHEMA AWAIT
BEGIN
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:0}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:20}) CREATE (n1)-[r:`DISTANCE` {`value`:12}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:0}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:22}) CREATE (n1)-[r:`DISTANCE` {`value`:20}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:20}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}) CREATE (n1)-[r:`DISTANCE` {`value`:5}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:21}) CREATE (n1)-[r:`DISTANCE` {`value`:5}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:21}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:22}) CREATE (n1)-[r:`DISTANCE` {`value`:7}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:20}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:42}) CREATE (n1)-[r:`DISTANCE` {`value`:15}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:22}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:23}) CREATE (n1)-[r:`DISTANCE` {`value`:5}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:0}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:41}) CREATE (n1)-[r:`DISTANCE` {`value`:16}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:44}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:0}) CREATE (n1)-[r:`DISTANCE` {`value`:4}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:44}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:41}) CREATE (n1)-[r:`DISTANCE` {`value`:6}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:42}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:44}) CREATE (n1)-[r:`DISTANCE` {`value`:21}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:43}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}) CREATE (n1)-[r:`DISTANCE` {`value`:15}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:0}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:21}) CREATE (n1)-[r:`DISTANCE` {`value`:19}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:20}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:21}) CREATE (n1)-[r:`DISTANCE` {`value`:13}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:23}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:0}) CREATE (n1)-[r:`DISTANCE` {`value`:5}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:41}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:23}) CREATE (n1)-[r:`DISTANCE` {`value`:11}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:44}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:20}) CREATE (n1)-[r:`DISTANCE` {`value`:19}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:42}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:43}) CREATE (n1)-[r:`DISTANCE` {`value`:10}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:43}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:20}) CREATE (n1)-[r:`DISTANCE` {`value`:7}]->(n2);
COMMIT
BEGIN
MATCH (n:`UNIQUE IMPORT LABEL`)  WITH n LIMIT 20000 REMOVE n:`UNIQUE IMPORT LABEL` REMOVE n.`UNIQUE IMPORT ID`;
COMMIT
BEGIN
DROP CONSTRAINT ON (node:`UNIQUE IMPORT LABEL`) ASSERT node.`UNIQUE IMPORT ID` IS UNIQUE;
COMMIT
